Feat: Submit dApp content
CasperDash/casperdash-mobile-wallet pull request #201
Opened 2023-08-07 17:12 UTC by hoailinh1210

### Summary (Please recap what you changed or fixed)

<img width="359" alt="image" src="https://github.com/CasperDash/casperdash-mobile-wallet/assets/20489407/e22ae8b8-4948-4383-b3ce-c9c805e83751">

### Checklist (If you won't pass this checklist please comment why)

-   [x] I removed all commented or unnecessary code.
-   [x] Provide the screenshots due to UI changed or bug fixed
-   [ ] My code has covered these test cases (please list down your tested cases):

2023-08-08 09:11 UTC, djhahe commented
@hoailinh1210 Pls get link from configurations API

2023-08-10 04:09 UTC, gaupoit commented
> Hi @gaupoit , please help me url to submit dApp.

Here you are https://forms.gle/jyyy6mNLTZduytQFA

2023-08-10 08:12 UTC, djhahe requested changes

2023-08-10 08:12 UTC, djhahe commented on src/screens/browser/components/HomePageContent/index.tsx
> +          <View>
Pls hide this if `configuration?.DAPP_SUBMIT_URL` is empty

2023-08-10 08:28 UTC, djhahe approved these changes

2023-08-10 08:29 UTC, merged